export const ELECTRON_CONFIG = {
  WINDOW: {
    WIDTH: 1280,
    HEIGHT: 800,
    MIN_WIDTH: 800,
    MIN_HEIGHT: 600,
    TITLE: "RawenChat",
  },
  DEV_URL: "http://localhost:3000",
} as const;
export const WINDOWS_KEY_MAP: Record<string, string> = {
  space: " ",
  enter: "{ENTER}",
  escape: "{ESC}",
  backspace: "{BACKSPACE}",
  tab: "{TAB}",
  up: "{UP}",
  down: "{DOWN}",
  left: "{LEFT}",
  right: "{RIGHT}",
  f1: "{F1}",
  f2: "{F2}",
  f3: "{F3}",
  f4: "{F4}",
  f5: "{F5}",
  f6: "{F6}",
  f7: "{F7}",
  f8: "{F8}",
  f9: "{F9}",
  f10: "{F10}",
  f11: "{F11}",
  f12: "{F12}",
};
export const LINUX_KEY_MAP: Record<string, string> = {
  space: "space",
  enter: "Return",
  escape: "Escape",
  backspace: "BackSpace",
  tab: "Tab",
  up: "Up",
  down: "Down",
  left: "Left",
  right: "Right",
  f1: "F1",
  f2: "F2",
  f3: "F3",
  f4: "F4",
  f5: "F5",
  f6: "F6",
  f7: "F7",
  f8: "F8",
  f9: "F9",
  f10: "F10",
  f11: "F11",
  f12: "F12",
};
export const MAC_KEY_MAP: Record<string, string> = {
  space: "space",
  enter: "Return",
  escape: "Escape",
  backspace: "BackSpace",
  tab: "Tab",
  up: "Up",
  down: "Down",
  left: "Left",
  right: "Right",
  f1: "F1",
  f2: "F2",
  f3: "F3",
  f4: "F4",
  f5: "F5",
  f6: "F6",
  f7: "F7",
  f8: "F8",
  f9: "F9",
  f10: "F10",
  f11: "F11",
  f12: "F12",
};
